# Generated by Django 5.0.3 on 2024-04-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_charithy_image_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('regular', 'regular'), ('government', 'government'), ('donor', 'donor')], default='donor', max_length=200),
        ),
    ]
