# Generated by Django 5.0.3 on 2024-05-15 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_needs_delete_charithy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charithy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=123)),
                ('middle_name', models.CharField(max_length=123)),
                ('last_name', models.CharField(max_length=123)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Profiles/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('sex', models.CharField(choices=[('male', 'M'), ('female', 'F')], default='male', max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('needs', models.ManyToManyField(to='users.needs')),
            ],
            options={
                'verbose_name_plural': 'Charithies',
                'ordering': ('age',),
            },
        ),
    ]
