# Generated by Django 5.0.3 on 2024-06-08 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_charithy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='needs',
            options={'verbose_name_plural': 'Needs'},
        ),
    ]
