# Generated by Django 5.0.3 on 2024-06-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0005_alter_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Events/'),
        ),
    ]
